# -*- coding: utf-8 -*-
"""coursera recommendation system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10JlFoD4nb9Jl61b8Pahm945ow-uRuOTa
"""

import numpy as np
import pandas as pd

df=pd.read_csv("/content/drive/MyDrive/Datasets/Coursera.csv")

df.head()

df.shape

df.drop(columns=['Course URL'],inplace=True)

df.isnull().sum()

df.head()

df['Course Name']=df['Course Name'].str.lower()
df['University']=df['University'].str.lower()
df['Course Description']=df['Course Description'].str.lower()
df['Skills']=df['Skills'].str.lower()

df.head()

df['tags'] = df['Course Name'] + df['Difficulty Level'] + df['Course Description'] + df['Skills']

new_df = df[['Course Name','tags']]

new_df

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000,stop_words='english')

vectors = cv.fit_transform(new_df['tags']).toarray()

vectors

from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

similarity

new_df['Course Name']

new_df.rename(columns = {'Course Name':'course_name'}, inplace = True)

def recommend(course):
    course_index = new_df[new_df['course_name'] == course].index[0]
    print(course_index)
    distances = similarity[course_index]
    print(distances)
    course_list = sorted(list(enumerate(distances)),reverse=True, key=lambda x:x[1])[1:7]

    for i in course_list:
        print(new_df.iloc[i[0]].course_name)

name="software testing and automation"
name=name.lower()

recommend(name)

import pickle

# Save
pickle.dump(new_df, open("course_df.pkl", "wb"))
pickle.dump(similarity, open("similarity.pkl", "wb"))

# Load
new_df = pickle.load(open("course_df.pkl", "rb"))
similarity = pickle.load(open("similarity.pkl", "rb"))